import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const BIKE_SESSIONS: SessionTemplate[] = [
  {
    id: 'bike-recovery',
    discipline: 'bike',
    sessionType: 'recovery',
    title: 'Récupération vélo',
    objective: 'Relancer les jambes sans créer de fatigue supplémentaire.',
    estimatedDurationMin: 30,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Roulage souple',
        durationSec: minutesToSec(30),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
  {
    id: 'bike-endurance',
    discipline: 'bike',
    sessionType: 'endurance',
    title: 'Endurance vélo',
    objective: 'Construire ta base aérobie à vélo, à une allure conversationnelle.',
    estimatedDurationMin: 70,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Roulage Z2',
        durationSec: minutesToSec(50),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-tempo',
    discipline: 'bike',
    sessionType: 'tempo',
    title: 'Tempo vélo',
    objective: 'Habituer ton corps à un effort soutenu mais gérable, sous le seuil.',
    estimatedDurationMin: 65,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(30),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-sweet-spot',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    title: 'Sweet Spot vélo',
    objective: 'Développer ta capacité à maintenir une puissance élevée durablement.',
    estimatedDurationMin: 65,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15, 'Échauffement progressif'),
      {
        label: 'Bloc Sweet Spot',
        durationSec: minutesToSec(8),
        repeat: 3,
        restSec: minutesToSec(4),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.sweetSpot[0],
        targetRpeMax: RPE_RANGE.sweetSpot[1],
        note: '88-92% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-threshold',
    discipline: 'bike',
    sessionType: 'threshold',
    title: 'Seuil vélo',
    objective: 'Repousser ton seuil fonctionnel (FTP) avec des blocs longs à haute intensité contrôlée.',
    estimatedDurationMin: 70,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(12),
        repeat: 2,
        restSec: minutesToSec(6),
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
        note: '95-100% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-vo2max',
    discipline: 'bike',
    sessionType: 'vo2max',
    title: 'VO2max vélo',
    objective: 'Améliorer ta puissance aérobie maximale sur des efforts courts et très intenses.',
    estimatedDurationMin: 60,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(15),
      {
        label: 'Répétition VO2max',
        durationSec: minutesToSec(3),
        repeat: 5,
        restSec: minutesToSec(3),
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
        note: '110-120% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-long',
    discipline: 'bike',
    sessionType: 'long',
    title: 'Sortie longue vélo',
    objective: 'Développer ton endurance de fond et ta capacité à durer à l\'effort.',
    estimatedDurationMin: 150,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Roulage endurance',
        durationSec: minutesToSec(120),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(15),
    ],
  },
]
