import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const BIKE_SESSIONS: SessionTemplate[] = [
  {
    id: 'bike-recovery',
    discipline: 'bike',
    sessionType: 'recovery',
    tier: 'standard',
    title: 'Récupération vélo',
    objective: 'Relancer les jambes sans créer de fatigue supplémentaire.',
    estimatedDurationMin: 30,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Roulage souple',
        durationSec: minutesToSec(30),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
  {
    id: 'bike-endurance',
    discipline: 'bike',
    sessionType: 'endurance',
    tier: 'standard',
    title: 'Endurance vélo',
    objective: 'Construire ta base aérobie à vélo, à une allure conversationnelle.',
    estimatedDurationMin: 70,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Roulage Z2',
        durationSec: minutesToSec(50),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },

  // --- Tempo — utilisé comme séance clé d'affûtage (brief §16/§18) : garde
  // le stimulus mais réduit nettement le volume à mesure que la course
  // approche (voir planning/progressionCurve.ts). ---
  {
    id: 'bike-tempo-minimal',
    discipline: 'bike',
    sessionType: 'tempo',
    tier: 'minimal',
    title: 'Tempo vélo (très allégé)',
    objective: 'Garder la sensation de rythme sans entamer la fraîcheur à quelques jours de la course.',
    estimatedDurationMin: 30,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(8),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(15),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(7),
    ],
  },
  {
    id: 'bike-tempo-reduced',
    discipline: 'bike',
    sessionType: 'tempo',
    tier: 'reduced',
    title: 'Tempo vélo (allégé)',
    objective: 'Maintenir le rythme de course en affûtage, avec un volume réduit.',
    estimatedDurationMin: 40,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(22),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'bike-tempo',
    discipline: 'bike',
    sessionType: 'tempo',
    tier: 'standard',
    title: 'Tempo vélo',
    objective: 'Habituer ton corps à un effort soutenu mais gérable, sous le seuil.',
    estimatedDurationMin: 65,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(30),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(10),
    ],
  },

  // --- Sweet Spot — séance clé de la phase développement. Deux structures
  // "standard" différentes (a/b) alternées d'une semaine sur l'autre pour
  // une vraie diversification, plus reduced/peak pour la progression au
  // fil des semaines du bloc. ---
  {
    id: 'bike-sweet-spot-reduced',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    tier: 'reduced',
    title: 'Sweet Spot vélo (allégé)',
    objective: 'Entretenir le stimulus sweet spot pendant une semaine de récupération du bloc.',
    estimatedDurationMin: 45,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15, 'Échauffement progressif'),
      {
        label: 'Bloc Sweet Spot',
        durationSec: minutesToSec(8),
        repeat: 2,
        restSec: minutesToSec(4),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.sweetSpot[0],
        targetRpeMax: RPE_RANGE.sweetSpot[1],
        note: '88-92% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-sweet-spot',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    tier: 'standard',
    title: 'Sweet Spot vélo',
    objective: 'Développer ta capacité à maintenir une puissance élevée durablement.',
    estimatedDurationMin: 65,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15, 'Échauffement progressif'),
      {
        label: 'Bloc Sweet Spot',
        durationSec: minutesToSec(8),
        repeat: 3,
        restSec: minutesToSec(4),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.sweetSpot[0],
        targetRpeMax: RPE_RANGE.sweetSpot[1],
        note: '88-92% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-sweet-spot-standard-b',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    tier: 'standard',
    title: 'Sweet Spot vélo — répétitions courtes',
    objective:
      'Même charge que la séance Sweet Spot classique, avec une structure différente pour varier le stimulus.',
    estimatedDurationMin: 55,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12, 'Échauffement progressif'),
      {
        label: 'Bloc Sweet Spot (répétitions courtes)',
        durationSec: minutesToSec(6),
        repeat: 4,
        restSec: minutesToSec(3),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.sweetSpot[0],
        targetRpeMax: RPE_RANGE.sweetSpot[1],
        note: '88-92% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-sweet-spot-peak',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    tier: 'peak',
    title: 'Sweet Spot vélo (semaine de pointe)',
    objective: 'La semaine la plus chargée du bloc développement : plus de volume à intensité sweet spot.',
    estimatedDurationMin: 77,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15, 'Échauffement progressif'),
      {
        label: 'Bloc Sweet Spot',
        durationSec: minutesToSec(10),
        repeat: 4,
        restSec: minutesToSec(4),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.sweetSpot[0],
        targetRpeMax: RPE_RANGE.sweetSpot[1],
        note: '88-92% FTP.',
      },
      cooldownBlock(10),
    ],
  },

  // --- Seuil — séance clé de la phase spécifique. ---
  {
    id: 'bike-threshold-reduced',
    discipline: 'bike',
    sessionType: 'threshold',
    tier: 'reduced',
    title: 'Seuil vélo (allégé)',
    objective: 'Entretenir le seuil pendant une semaine de récupération du bloc spécifique.',
    estimatedDurationMin: 43,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(8),
        repeat: 2,
        restSec: minutesToSec(5),
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
        note: '95-100% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-threshold',
    discipline: 'bike',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil vélo',
    objective: 'Repousser ton seuil fonctionnel (FTP) avec des blocs longs à haute intensité contrôlée.',
    estimatedDurationMin: 70,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(12),
        repeat: 2,
        restSec: minutesToSec(6),
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
        note: '95-100% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-threshold-standard-b',
    discipline: 'bike',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil vélo — répétitions courtes',
    objective: 'Même charge que la séance Seuil classique, avec des répétitions plus courtes et nombreuses.',
    estimatedDurationMin: 61,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Bloc seuil (répétitions courtes)',
        durationSec: minutesToSec(6),
        repeat: 4,
        restSec: minutesToSec(4),
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
        note: '95-100% FTP.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-threshold-peak',
    discipline: 'bike',
    sessionType: 'threshold',
    tier: 'peak',
    title: 'Seuil vélo (semaine de pointe)',
    objective: 'La semaine la plus exigeante du bloc spécifique : plus de temps passé au seuil.',
    estimatedDurationMin: 71,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(12),
        repeat: 3,
        restSec: minutesToSec(5),
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
        note: '95-100% FTP.',
      },
      cooldownBlock(10),
    ],
  },

  {
    id: 'bike-vo2max',
    discipline: 'bike',
    sessionType: 'vo2max',
    tier: 'standard',
    title: 'VO2max vélo',
    objective: 'Améliorer ta puissance aérobie maximale sur des efforts courts et très intenses.',
    estimatedDurationMin: 60,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(15),
      {
        label: 'Répétition VO2max',
        durationSec: minutesToSec(3),
        repeat: 5,
        restSec: minutesToSec(3),
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
        note: '110-120% FTP.',
      },
      cooldownBlock(10),
    ],
  },

  // --- Sortie longue — ancre de la phase base, puis touche d'endurance
  // qui persiste (sous forme de séance secondaire) en développement et
  // spécifique plutôt que de disparaître dès la fin de la base. ---
  {
    id: 'bike-long-reduced',
    discipline: 'bike',
    sessionType: 'long',
    tier: 'reduced',
    title: 'Sortie longue vélo (allégée)',
    objective: 'Garder le contact avec la durée pendant une semaine de récupération.',
    estimatedDurationMin: 90,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Roulage endurance',
        durationSec: minutesToSec(70),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'bike-long',
    discipline: 'bike',
    sessionType: 'long',
    tier: 'standard',
    title: 'Sortie longue vélo',
    objective: 'Développer ton endurance de fond et ta capacité à durer à l\'effort.',
    estimatedDurationMin: 150,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Roulage endurance',
        durationSec: minutesToSec(120),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(15),
    ],
  },
  {
    id: 'bike-long-standard-b',
    discipline: 'bike',
    sessionType: 'long',
    tier: 'standard',
    title: 'Sortie longue vélo avec finish tempo',
    objective:
      'Même durée que la sortie longue classique, avec une portion à allure tempo en fin de séance pour habituer le corps à produire un effort soutenu sur des jambes fatiguées — utile en développement/spécifique.',
    estimatedDurationMin: 150,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Roulage endurance',
        durationSec: minutesToSec(100),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      {
        label: 'Finish tempo',
        durationSec: minutesToSec(20),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
        note: 'Les dernières minutes de la sortie longue, aux sensations de course.',
      },
      cooldownBlock(15),
    ],
  },
  {
    id: 'bike-long-peak',
    discipline: 'bike',
    sessionType: 'long',
    tier: 'peak',
    title: 'Sortie longue vélo (semaine de pointe)',
    objective: 'La sortie longue la plus exigeante du bloc, avec une portion tempo prolongée.',
    estimatedDurationMin: 175,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Roulage endurance',
        durationSec: minutesToSec(125),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      {
        label: 'Finish tempo',
        durationSec: minutesToSec(20),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
        note: 'Les dernières minutes de la sortie longue, aux sensations de course.',
      },
      cooldownBlock(15),
    ],
  },

  // --- Cadence — travail neuromusculaire/technique, complément à faible
  // coût de fatigue plutôt qu'un stimulus supplémentaire à part entière. ---
  {
    id: 'bike-cadence-drills',
    discipline: 'bike',
    sessionType: 'technique',
    tier: 'standard',
    title: 'Travail de cadence',
    objective:
      "Améliore ton efficacité de pédalage par des blocs à cadence élevée, sans intensité — un stimulus neuromusculaire léger plutôt qu'un vrai effort.",
    estimatedDurationMin: 30,
    defaultPriority: 'optional',
    blocks: [
      warmupBlock(8),
      {
        label: 'Cadence élevée (>100 rpm)',
        durationSec: minutesToSec(1),
        repeat: 6,
        restSec: 90,
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.easy[0],
        targetRpeMax: RPE_RANGE.easy[1],
        note: 'Braquet léger, cadence élevée, relâché — la vitesse vient de la fréquence de pédalage, pas de la force.',
      },
      cooldownBlock(8),
    ],
  },

  // --- Allure course — spécificité pure, distincte de l'endurance/tempo :
  // reproduit précisément l'intensité cible du jour J plutôt qu'une zone
  // générique. ---
  {
    id: 'bike-race-specific',
    discipline: 'bike',
    sessionType: 'race-specific',
    tier: 'standard',
    title: 'Bloc allure course vélo',
    objective:
      "Répète ton allure/puissance cible de course vélo en continu — la répétition la plus spécifique possible de ta portion vélo, hors brick.",
    estimatedDurationMin: 70,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(15),
      {
        label: 'Bloc allure course',
        durationSec: minutesToSec(40),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
        note: 'À ta puissance/allure cible de course exacte, pas plus — la spécificité prime sur la performance du jour.',
      },
      cooldownBlock(15),
    ],
  },
]
