import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const RUN_SESSIONS: SessionTemplate[] = [
  {
    id: 'run-recovery',
    discipline: 'run',
    sessionType: 'recovery',
    title: 'Footing récupération',
    objective: 'Favoriser la récupération par un footing très facile, sans regarder l\'allure.',
    estimatedDurationMin: 25,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Footing très facile',
        durationSec: minutesToSec(25),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
  {
    id: 'run-easy',
    discipline: 'run',
    sessionType: 'endurance',
    title: 'Footing facile',
    objective: 'Construire ta base aérobie en course à pied à une allure conversationnelle.',
    estimatedDurationMin: 40,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(5),
      {
        label: 'Footing Z2',
        durationSec: minutesToSec(30),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(5),
    ],
  },
  {
    id: 'run-long',
    discipline: 'run',
    sessionType: 'long',
    title: 'Sortie longue course',
    objective: 'Développer ton endurance de fond et ta résistance à la fatigue sur la durée.',
    estimatedDurationMin: 75,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Endurance fondamentale',
        durationSec: minutesToSec(55),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-tempo',
    discipline: 'run',
    sessionType: 'tempo',
    title: 'Tempo course',
    objective: 'Habituer ton corps à courir vite tout en restant contrôlé.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(20),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-threshold',
    discipline: 'run',
    sessionType: 'threshold',
    title: 'Seuil course',
    objective: 'Repousser ton allure seuil avec des blocs longs à intensité contrôlée.',
    estimatedDurationMin: 50,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(8),
        repeat: 3,
        restSec: 90,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-intervals',
    discipline: 'run',
    sessionType: 'intervals',
    title: 'Fractionné course',
    objective: 'Développer ta VO2max et ta vitesse maximale aérobie.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(12),
      {
        label: '400m rapide',
        durationSec: minutesToSec(2),
        repeat: 8,
        restSec: 90,
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
      },
      cooldownBlock(10),
    ],
  },
]
