import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const RUN_SESSIONS: SessionTemplate[] = [
  {
    id: 'run-recovery',
    discipline: 'run',
    sessionType: 'recovery',
    tier: 'standard',
    title: 'Footing récupération',
    objective: 'Favoriser la récupération par un footing très facile, sans regarder l\'allure.',
    estimatedDurationMin: 25,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Footing très facile',
        durationSec: minutesToSec(25),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
  {
    id: 'run-easy',
    discipline: 'run',
    sessionType: 'endurance',
    tier: 'standard',
    title: 'Footing facile',
    objective: 'Construire ta base aérobie en course à pied à une allure conversationnelle.',
    estimatedDurationMin: 40,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(5),
      {
        label: 'Footing Z2',
        durationSec: minutesToSec(30),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(5),
    ],
  },

  // --- Sortie longue — ancre de la phase base, puis touche d'endurance
  // qui persiste en développement/spécifique via la rotation des séances
  // secondaires (planning/weeklySlots.ts). ---
  {
    id: 'run-long-reduced',
    discipline: 'run',
    sessionType: 'long',
    tier: 'reduced',
    title: 'Sortie longue course (allégée)',
    objective: 'Garder le contact avec la durée pendant une semaine de récupération.',
    estimatedDurationMin: 45,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(5),
      {
        label: 'Endurance fondamentale',
        durationSec: minutesToSec(35),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(5),
    ],
  },
  {
    id: 'run-long',
    discipline: 'run',
    sessionType: 'long',
    tier: 'standard',
    title: 'Sortie longue course',
    objective: 'Développer ton endurance de fond et ta résistance à la fatigue sur la durée.',
    estimatedDurationMin: 75,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Endurance fondamentale',
        durationSec: minutesToSec(55),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-long-standard-b',
    discipline: 'run',
    sessionType: 'long',
    tier: 'standard',
    title: 'Sortie longue course avec finish rapide',
    objective:
      'Même durée que la sortie longue classique, avec les dernières minutes accélérées pour habituer les jambes à finir vite sur de la fatigue.',
    estimatedDurationMin: 80,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Endurance fondamentale',
        durationSec: minutesToSec(50),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      {
        label: 'Finish rapide',
        durationSec: minutesToSec(10),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
        note: 'Les dernières minutes de la sortie longue, aux sensations de course.',
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-long-peak',
    discipline: 'run',
    sessionType: 'long',
    tier: 'peak',
    title: 'Sortie longue course (semaine de pointe)',
    objective: 'La sortie longue la plus exigeante du bloc, avec un finish rapide plus long.',
    estimatedDurationMin: 100,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Endurance fondamentale',
        durationSec: minutesToSec(65),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      {
        label: 'Finish rapide',
        durationSec: minutesToSec(15),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
        note: 'Les dernières minutes de la sortie longue, aux sensations de course.',
      },
      cooldownBlock(10),
    ],
  },

  // --- Tempo — clé de la phase développement ET de l'affûtage (allures
  // plus légères en taper). Deux structures standard (continue / fractionnée)
  // pour varier le stimulus d'une semaine sur l'autre. ---
  {
    id: 'run-tempo-minimal',
    discipline: 'run',
    sessionType: 'tempo',
    tier: 'minimal',
    title: 'Tempo course (très allégé)',
    objective: 'Garder la sensation de rythme sans entamer la fraîcheur à quelques jours de la course.',
    estimatedDurationMin: 23,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(8),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(8),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(7),
    ],
  },
  {
    id: 'run-tempo-reduced',
    discipline: 'run',
    sessionType: 'tempo',
    tier: 'reduced',
    title: 'Tempo course (allégé)',
    objective: 'Entretenir le rythme de course pendant une semaine de récupération du bloc.',
    estimatedDurationMin: 33,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(15),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'run-tempo',
    discipline: 'run',
    sessionType: 'tempo',
    tier: 'standard',
    title: 'Tempo course',
    objective: 'Habituer ton corps à courir vite tout en restant contrôlé.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(20),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-tempo-standard-b',
    discipline: 'run',
    sessionType: 'tempo',
    tier: 'standard',
    title: 'Tempo course — bloc fractionné',
    objective: 'Même charge que la séance Tempo classique, coupée en deux blocs pour varier le stimulus.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(12),
        repeat: 2,
        restSec: minutesToSec(3),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'run-tempo-peak',
    discipline: 'run',
    sessionType: 'tempo',
    tier: 'peak',
    title: 'Tempo course (semaine de pointe)',
    objective: 'La semaine la plus chargée du bloc développement pour le tempo.',
    estimatedDurationMin: 50,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc tempo',
        durationSec: minutesToSec(30),
        targetZone: 'Z3',
        targetRpeMin: RPE_RANGE.tempo[0],
        targetRpeMax: RPE_RANGE.tempo[1],
      },
      cooldownBlock(10),
    ],
  },

  // --- Seuil — clé de la phase spécifique. ---
  {
    id: 'run-threshold-reduced',
    discipline: 'run',
    sessionType: 'threshold',
    tier: 'reduced',
    title: 'Seuil course (allégé)',
    objective: 'Entretenir le seuil pendant une semaine de récupération du bloc spécifique.',
    estimatedDurationMin: 34,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(6),
        repeat: 2,
        restSec: 90,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-threshold',
    discipline: 'run',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil course',
    objective: 'Repousser ton allure seuil avec des blocs longs à intensité contrôlée.',
    estimatedDurationMin: 50,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(8),
        repeat: 3,
        restSec: 90,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-threshold-standard-b',
    discipline: 'run',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil course — répétitions courtes',
    objective: 'Même charge que la séance Seuil classique, avec des répétitions plus courtes et nombreuses.',
    estimatedDurationMin: 46,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: 'Bloc seuil (répétitions courtes)',
        durationSec: minutesToSec(4),
        repeat: 5,
        restSec: 90,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'run-threshold-peak',
    discipline: 'run',
    sessionType: 'threshold',
    tier: 'peak',
    title: 'Seuil course (semaine de pointe)',
    objective: 'La semaine la plus exigeante du bloc spécifique : plus de temps passé au seuil.',
    estimatedDurationMin: 59,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: 'Bloc seuil',
        durationSec: minutesToSec(8),
        repeat: 4,
        restSec: 90,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(10),
    ],
  },

  {
    id: 'run-intervals',
    discipline: 'run',
    sessionType: 'intervals',
    tier: 'standard',
    title: 'Fractionné course',
    objective: 'Développer ta VO2max et ta vitesse maximale aérobie.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(12),
      {
        label: '400m rapide',
        durationSec: minutesToSec(2),
        repeat: 8,
        restSec: 90,
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
      },
      cooldownBlock(10),
    ],
  },
]
