import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const SWIM_SESSIONS: SessionTemplate[] = [
  {
    id: 'swim-technique',
    discipline: 'swim',
    sessionType: 'technique',
    title: 'Technique natation',
    objective:
      'Améliorer ton efficacité de nage (position, respiration, catch) pour nager plus vite sans plus d\'effort.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10, 'Échauffement libre'),
      {
        label: 'Exercices techniques',
        durationSec: minutesToSec(4),
        repeat: 6,
        restSec: 20,
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.easy[0],
        targetRpeMax: RPE_RANGE.easy[1],
        note: 'Éducatifs : catch-up, doigts traînants, respiration bilatérale.',
      },
      cooldownBlock(5),
    ],
  },
  {
    id: 'swim-endurance',
    discipline: 'swim',
    sessionType: 'endurance',
    title: 'Endurance natation',
    objective: 'Construire ta base aérobie en natation avec un nage continue régulière.',
    estimatedDurationMin: 50,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Nage continue',
        durationSec: minutesToSec(30),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'swim-css',
    discipline: 'swim',
    sessionType: 'css',
    title: 'Répétitions CSS',
    objective:
      'Travailler à ton allure critique (CSS) pour améliorer ta capacité à maintenir un rythme soutenu.',
    estimatedDurationMin: 55,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '400m à allure CSS',
        durationSec: minutesToSec(7),
        distanceMeters: 400,
        repeat: 4,
        restSec: 30,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-threshold',
    discipline: 'swim',
    sessionType: 'threshold',
    title: 'Seuil natation',
    objective: 'Repousser ton seuil en nageant juste sous ton allure critique sur des séries longues.',
    estimatedDurationMin: 60,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: '3 x 600m allure seuil',
        durationSec: minutesToSec(10),
        distanceMeters: 600,
        repeat: 3,
        restSec: 40,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-intervals',
    discipline: 'swim',
    sessionType: 'intervals',
    title: 'Fractionné court natation',
    objective: 'Développer ta puissance et ta VO2max en natation sur des répétitions courtes et intenses.',
    estimatedDurationMin: 50,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: '100m rapide',
        durationSec: minutesToSec(2),
        distanceMeters: 100,
        repeat: 10,
        restSec: 30,
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'swim-recovery',
    discipline: 'swim',
    sessionType: 'recovery',
    title: 'Récupération natation',
    objective: 'Favoriser la récupération active par une nage très facile.',
    estimatedDurationMin: 25,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Nage libre très facile',
        durationSec: minutesToSec(25),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
]
