import {
  cooldownBlock,
  minutesToSec,
  RPE_RANGE,
  warmupBlock,
  type SessionTemplate,
} from './common'

export const SWIM_SESSIONS: SessionTemplate[] = [
  // --- Technique — ancre de la phase base. ---
  {
    id: 'swim-technique-reduced',
    discipline: 'swim',
    sessionType: 'technique',
    tier: 'reduced',
    title: 'Technique natation (allégée)',
    objective: 'Entretenir le travail technique pendant une semaine de récupération.',
    estimatedDurationMin: 30,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(8, 'Échauffement libre'),
      {
        label: 'Exercices techniques',
        durationSec: minutesToSec(4),
        repeat: 4,
        restSec: 20,
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.easy[0],
        targetRpeMax: RPE_RANGE.easy[1],
        note: 'Éducatifs : catch-up, doigts traînants, respiration bilatérale.',
      },
      cooldownBlock(5),
    ],
  },
  {
    id: 'swim-technique',
    discipline: 'swim',
    sessionType: 'technique',
    tier: 'standard',
    title: 'Technique natation',
    objective:
      'Améliorer ton efficacité de nage (position, respiration, catch) pour nager plus vite sans plus d\'effort.',
    estimatedDurationMin: 45,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10, 'Échauffement libre'),
      {
        label: 'Exercices techniques',
        durationSec: minutesToSec(4),
        repeat: 6,
        restSec: 20,
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.easy[0],
        targetRpeMax: RPE_RANGE.easy[1],
        note: 'Éducatifs : catch-up, doigts traînants, respiration bilatérale.',
      },
      cooldownBlock(5),
    ],
  },
  {
    id: 'swim-technique-peak',
    discipline: 'swim',
    sessionType: 'technique',
    tier: 'peak',
    title: 'Technique natation (semaine de pointe)',
    objective: 'La semaine la plus chargée du bloc base pour le travail technique.',
    estimatedDurationMin: 54,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(12, 'Échauffement libre'),
      {
        label: 'Exercices techniques',
        durationSec: minutesToSec(4),
        repeat: 8,
        restSec: 20,
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.easy[0],
        targetRpeMax: RPE_RANGE.easy[1],
        note: 'Éducatifs : catch-up, doigts traînants, respiration bilatérale.',
      },
      cooldownBlock(8),
    ],
  },

  // --- Endurance — clé de l'affûtage, secondaire ailleurs. ---
  {
    id: 'swim-endurance-minimal',
    discipline: 'swim',
    sessionType: 'endurance',
    tier: 'minimal',
    title: 'Endurance natation (très allégée)',
    objective: 'Garder la sensation de l\'eau sans entamer la fraîcheur à quelques jours de la course.',
    estimatedDurationMin: 30,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(8),
      {
        label: 'Nage continue',
        durationSec: minutesToSec(15),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(7),
    ],
  },
  {
    id: 'swim-endurance-reduced',
    discipline: 'swim',
    sessionType: 'endurance',
    tier: 'reduced',
    title: 'Endurance natation (allégée)',
    objective: 'Entretenir l\'endurance pendant une semaine de récupération.',
    estimatedDurationMin: 40,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Nage continue',
        durationSec: minutesToSec(22),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-endurance',
    discipline: 'swim',
    sessionType: 'endurance',
    tier: 'standard',
    title: 'Endurance natation',
    objective: 'Construire ta base aérobie en natation avec un nage continue régulière.',
    estimatedDurationMin: 50,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: 'Nage continue',
        durationSec: minutesToSec(30),
        targetZone: 'Z2',
        targetRpeMin: RPE_RANGE.endurance[0],
        targetRpeMax: RPE_RANGE.endurance[1],
      },
      cooldownBlock(10),
    ],
  },

  // --- CSS — clé de la phase développement. ---
  {
    id: 'swim-css-reduced',
    discipline: 'swim',
    sessionType: 'css',
    tier: 'reduced',
    title: 'Répétitions CSS (allégées)',
    objective: 'Entretenir l\'allure critique pendant une semaine de récupération du bloc.',
    estimatedDurationMin: 40,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '400m à allure CSS',
        durationSec: minutesToSec(7),
        distanceMeters: 400,
        repeat: 3,
        restSec: 30,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-css',
    discipline: 'swim',
    sessionType: 'css',
    tier: 'standard',
    title: 'Répétitions CSS',
    objective:
      'Travailler à ton allure critique (CSS) pour améliorer ta capacité à maintenir un rythme soutenu.',
    estimatedDurationMin: 55,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '400m à allure CSS',
        durationSec: minutesToSec(7),
        distanceMeters: 400,
        repeat: 4,
        restSec: 30,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-css-standard-b',
    discipline: 'swim',
    sessionType: 'css',
    tier: 'standard',
    title: 'Répétitions CSS — répétitions courtes',
    objective: 'Même charge que la séance CSS classique, sur des répétitions plus courtes et nombreuses.',
    estimatedDurationMin: 48,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '200m à allure CSS',
        durationSec: minutesToSec(3.5),
        distanceMeters: 200,
        repeat: 8,
        restSec: 20,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-css-peak',
    discipline: 'swim',
    sessionType: 'css',
    tier: 'peak',
    title: 'Répétitions CSS (semaine de pointe)',
    objective: 'La semaine la plus chargée du bloc développement pour le CSS.',
    estimatedDurationMin: 62,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '400m à allure CSS',
        durationSec: minutesToSec(7),
        distanceMeters: 400,
        repeat: 6,
        restSec: 25,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },

  // --- Seuil — clé de la phase spécifique. ---
  {
    id: 'swim-threshold-reduced',
    discipline: 'swim',
    sessionType: 'threshold',
    tier: 'reduced',
    title: 'Seuil natation (allégé)',
    objective: 'Entretenir le seuil pendant une semaine de récupération du bloc spécifique.',
    estimatedDurationMin: 39,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '2 x 600m allure seuil',
        durationSec: minutesToSec(10),
        distanceMeters: 600,
        repeat: 2,
        restSec: 40,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-threshold',
    discipline: 'swim',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil natation',
    objective: 'Repousser ton seuil en nageant juste sous ton allure critique sur des séries longues.',
    estimatedDurationMin: 60,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: '3 x 600m allure seuil',
        durationSec: minutesToSec(10),
        distanceMeters: 600,
        repeat: 3,
        restSec: 40,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-threshold-standard-b',
    discipline: 'swim',
    sessionType: 'threshold',
    tier: 'standard',
    title: 'Seuil natation — répétitions courtes',
    objective: 'Même charge que la séance Seuil classique, sur des répétitions plus courtes et nombreuses.',
    estimatedDurationMin: 51,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(10),
      {
        label: '6 x 300m allure seuil',
        durationSec: minutesToSec(5),
        distanceMeters: 300,
        repeat: 6,
        restSec: 30,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },
  {
    id: 'swim-threshold-peak',
    discipline: 'swim',
    sessionType: 'threshold',
    tier: 'peak',
    title: 'Seuil natation (semaine de pointe)',
    objective: 'La semaine la plus exigeante du bloc spécifique : plus de séries au seuil.',
    estimatedDurationMin: 62,
    defaultPriority: 'key',
    blocks: [
      warmupBlock(12),
      {
        label: '6 x 400m allure seuil',
        durationSec: minutesToSec(7),
        distanceMeters: 400,
        repeat: 6,
        restSec: 25,
        targetZone: 'Z4',
        targetRpeMin: RPE_RANGE.threshold[0],
        targetRpeMax: RPE_RANGE.threshold[1],
      },
      cooldownBlock(8),
    ],
  },

  {
    id: 'swim-intervals',
    discipline: 'swim',
    sessionType: 'intervals',
    tier: 'standard',
    title: 'Fractionné court natation',
    objective: 'Développer ta puissance et ta VO2max en natation sur des répétitions courtes et intenses.',
    estimatedDurationMin: 50,
    defaultPriority: 'secondary',
    blocks: [
      warmupBlock(10),
      {
        label: '100m rapide',
        durationSec: minutesToSec(2),
        distanceMeters: 100,
        repeat: 10,
        restSec: 30,
        targetZone: 'Z5',
        targetRpeMin: RPE_RANGE.vo2max[0],
        targetRpeMax: RPE_RANGE.vo2max[1],
      },
      cooldownBlock(10),
    ],
  },
  {
    id: 'swim-recovery',
    discipline: 'swim',
    sessionType: 'recovery',
    tier: 'standard',
    title: 'Récupération natation',
    objective: 'Favoriser la récupération active par une nage très facile.',
    estimatedDurationMin: 25,
    defaultPriority: 'optional',
    blocks: [
      {
        label: 'Nage libre très facile',
        durationSec: minutesToSec(25),
        targetZone: 'Z1',
        targetRpeMin: RPE_RANGE.recovery[0],
        targetRpeMax: RPE_RANGE.recovery[1],
      },
    ],
  },
]
