import type { EvidenceClassification } from '@/core/coaching/evidenceClassification'
import type { WorkoutFamily } from '@/core/coaching/workoutFamily'

/**
 * The concrete triathlon Workout Family registry (brief §9–§10) — an
 * *annotation layer* over the existing session catalog
 * (`sports/triathlon/sessions/`), not a replacement for it. Every entry
 * corresponds to a real `(discipline, SessionType)` pair that already has
 * authored `SessionTemplate`s; `getFamilyForSession` is how
 * `buildWeekSessions.ts`/the Weekly Composer resolve "which family does
 * this slot belong to" without duplicating catalog knowledge.
 *
 * A few brief-named families are deliberately *not* separate registry
 * entries here — see `docs/workout-families.md` for the full rationale:
 * - `SWIM_TEMPO` is folded into `SWIM_ENDURANCE`: swim training doesn't
 *   distinguish a moderate-sustained tier the way run/bike do once
 *   CSS/threshold already cover the sub-threshold-to-threshold range.
 * - `SWIM_OPEN_WATER` has no catalog template yet and is intentionally
 *   never selected — the product has no way to know an athlete has safe
 *   open-water access (brief §19's own caution), so scheduling it would
 *   be an unfounded assumption, not a coaching decision.
 */
const H = 'COACHING_HEURISTIC' as const satisfies EvidenceClassification
const E = 'EVIDENCE_BASED' as const satisfies EvidenceClassification
const P = 'PRODUCT_RULE' as const satisfies EvidenceClassification

export const WORKOUT_FAMILIES: Record<string, WorkoutFamily> = {
  // ---------------------------------------------------------------- SWIM
  SWIM_TECHNIQUE: {
    id: 'SWIM_TECHNIQUE',
    discipline: 'swim',
    sessionType: 'technique',
    trainingPurpose: 'Améliorer la position du corps, la respiration, le catch/pull et la coordination.',
    physiologicalIntent: "Efficacité de nage — réduire le coût énergétique par mètre plutôt qu'augmenter l'effort.",
    appropriatePhases: ['base', 'build'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    progressionLevels: 3,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'SUPPORT',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    compatibleNeighbors: ['BIKE_THRESHOLD', 'RUN_THRESHOLD'],
    fallbackPrescription: 'RPE + repères techniques (sensations), jamais de cible chronométrée.',
    explanation:
      "Un nageur faible progresse davantage avec du travail technique ciblé qu'avec plus de volume au même défaut technique.",
    evidenceClassification: E,
  },
  SWIM_ENDURANCE: {
    id: 'SWIM_ENDURANCE',
    discipline: 'swim',
    sessionType: 'endurance',
    trainingPurpose: 'Construire le volume de nage soutenable et la tolérance à la durée.',
    physiologicalIntent: 'Base aérobie natation.',
    appropriatePhases: ['base', 'build', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'EASY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE (conversationnel) — la CSS affine mais ne conditionne pas cette famille.',
    explanation: 'Construit ta base aérobie natation à un rythme conversationnel.',
    evidenceClassification: E,
  },
  SWIM_CSS: {
    id: 'SWIM_CSS',
    discipline: 'swim',
    sessionType: 'css',
    trainingPurpose: 'Développer la vitesse soutenable sur la durée (Critical Swim Speed).',
    physiologicalIntent: 'Seuil aérobie/anaérobie natation.',
    appropriatePhases: ['build'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 4,
    minimumEffectiveDurationMin: 25,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['SWIM_THRESHOLD'],
    requiredMetric: ['cssSecPer100m'],
    fallbackPrescription: 'RPE (seuil) sans allure /100m précise tant que la CSS n\'est pas testée.',
    explanation: 'Repousse ta vitesse de nage soutenable — la référence pour toutes tes allures de nage.',
    evidenceClassification: E,
  },
  SWIM_THRESHOLD: {
    id: 'SWIM_THRESHOLD',
    discipline: 'swim',
    sessionType: 'threshold',
    trainingPurpose: 'Consolider la CSS en blocs plus longs, plus proches de la spécificité course.',
    physiologicalIntent: 'Seuil natation, exposition prolongée.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 4,
    minimumEffectiveDurationMin: 30,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['SWIM_CSS'],
    requiredMetric: ['cssSecPer100m'],
    fallbackPrescription: 'RPE (seuil).',
    explanation: 'Consolide ta vitesse seuil sur des blocs plus longs, plus proches de ta course.',
    evidenceClassification: H,
  },
  SWIM_SPEED: {
    id: 'SWIM_SPEED',
    discipline: 'swim',
    sessionType: 'intervals',
    trainingPurpose: 'Répétitions courtes et rapides avec récupération complète.',
    physiologicalIntent: 'Puissance/vitesse maximale natation, faible accumulation de fatigue.',
    appropriatePhases: ['build', 'specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'secondary' },
    progressionLevels: 3,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'SUPPORT',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    fallbackPrescription: 'RPE (proche du maximal, sur des répétitions courtes).',
    explanation: "Développe ta vitesse de pointe — plus déterminante sur un Sprint que sur un M.",
    evidenceClassification: H,
  },
  SWIM_RECOVERY: {
    id: 'SWIM_RECOVERY',
    discipline: 'swim',
    sessionType: 'recovery',
    trainingPurpose: 'Récupération active sans ajouter de fatigue.',
    physiologicalIntent: 'Circulation, relâchement technique.',
    appropriatePhases: ['base', 'build', 'specific', 'taper', 'race'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'RECOVERY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE très facile uniquement.',
    explanation: 'Relance la circulation sans ajouter de fatigue.',
    evidenceClassification: H,
  },

  // ---------------------------------------------------------------- BIKE
  BIKE_ENDURANCE: {
    id: 'BIKE_ENDURANCE',
    discipline: 'bike',
    sessionType: 'endurance',
    trainingPurpose: 'Construire la base aérobie à vélo.',
    physiologicalIntent: 'Base aérobie, densité mitochondriale, utilisation des graisses.',
    appropriatePhases: ['base', 'build', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'EASY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE (conversationnel) — %FTP affine si connu.',
    explanation: 'Construit ta base aérobie à vélo, à une allure conversationnelle.',
    evidenceClassification: E,
  },
  BIKE_TEMPO: {
    id: 'BIKE_TEMPO',
    discipline: 'bike',
    sessionType: 'tempo',
    trainingPurpose: 'Travail sous-seuil soutenu.',
    physiologicalIntent: 'Endurance musculaire, tolérance à un effort modéré prolongé.',
    appropriatePhases: ['build'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'secondary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 25,
    defaultPriority: 'SUPPORT',
    fatigueCost: 'moderate',
    recoveryRequirement: 0,
    requiredMetric: ['ftpWatts'],
    fallbackPrescription: 'RPE (modéré-soutenu) sans %FTP tant que la FTP n\'est pas testée.',
    explanation: 'Développe ta capacité à rouler soutenu sans être au maximum.',
    evidenceClassification: H,
  },
  BIKE_SWEET_SPOT: {
    id: 'BIKE_SWEET_SPOT',
    discipline: 'bike',
    sessionType: 'sweet-spot',
    trainingPurpose: "Développer la puissance soutenable juste sous le seuil (88-94% FTP).",
    physiologicalIntent: 'Le meilleur ratio charge/fatigue pour développer la puissance seuil.',
    appropriatePhases: ['build'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'secondary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 4,
    minimumEffectiveDurationMin: 30,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['BIKE_THRESHOLD', 'BIKE_VO2'],
    requiredMetric: ['ftpWatts'],
    fallbackPrescription: 'RPE (soutenu-difficile) sans %FTP tant que la FTP n\'est pas testée.',
    explanation: 'Le meilleur compromis charge/fatigue pour progresser vers ton seuil.',
    evidenceClassification: E,
  },
  BIKE_THRESHOLD: {
    id: 'BIKE_THRESHOLD',
    discipline: 'bike',
    sessionType: 'threshold',
    trainingPurpose: 'Développer la puissance seuil (FTP).',
    physiologicalIntent: 'Seuil fonctionnel de puissance.',
    appropriatePhases: ['build', 'specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 5,
    minimumEffectiveDurationMin: 35,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['BIKE_SWEET_SPOT', 'BIKE_VO2', 'RUN_THRESHOLD'],
    requiredMetric: ['ftpWatts'],
    fallbackPrescription: 'RPE (seuil, 7-8/10) sans %FTP tant que la FTP n\'est pas testée.',
    explanation: 'Repousse ta FTP — la référence pour toutes tes allures vélo.',
    evidenceClassification: E,
  },
  BIKE_VO2: {
    id: 'BIKE_VO2',
    discipline: 'bike',
    sessionType: 'vo2max',
    trainingPurpose: 'Développer la puissance aérobie maximale.',
    physiologicalIntent: 'VO2max, forte sollicitation cardio-respiratoire.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'minor' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 4,
    minimumEffectiveDurationMin: 25,
    defaultPriority: 'KEY_B',
    fatigueCost: 'high',
    recoveryRequirement: 2,
    incompatibleNeighbors: ['BIKE_THRESHOLD', 'BIKE_SWEET_SPOT', 'RUN_VO2', 'BRICK_SPECIFIC'],
    requiredMetric: ['ftpWatts'],
    fallbackPrescription: 'RPE (quasi-maximal, 8-9/10).',
    explanation: 'Coût physiologique élevé : utilisé sélectivement, jamais "parce que la semaine a besoin d\'intensité".',
    evidenceClassification: E,
  },
  BIKE_LONG: {
    id: 'BIKE_LONG',
    discipline: 'bike',
    sessionType: 'long',
    trainingPurpose: 'Développer la durabilité et la résistance à la fatigue sur la durée.',
    physiologicalIntent: 'Base aérobie longue durée, économie sur la durée.',
    appropriatePhases: ['base', 'build', 'specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 60,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['RUN_LONG'],
    fallbackPrescription: 'RPE (endurance) — %FTP affine si connu.',
    explanation: "L'ancre de la semaine pour la durabilité à vélo.",
    evidenceClassification: E,
  },
  BIKE_CADENCE: {
    id: 'BIKE_CADENCE',
    discipline: 'bike',
    sessionType: 'technique',
    trainingPurpose: 'Améliorer l\'efficacité de pédalage.',
    physiologicalIntent: 'Neuromusculaire, coordination — pas un stimulus cardiovasculaire.',
    appropriatePhases: ['base', 'build'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 2,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'OPTIONAL',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'Sensation de fluidité, pas de cible chronométrée.',
    explanation: "Un complément à faible coût, jamais un stimulus supplémentaire à part entière.",
    evidenceClassification: H,
  },
  BIKE_RACE_SPECIFIC: {
    id: 'BIKE_RACE_SPECIFIC',
    discipline: 'bike',
    sessionType: 'race-specific',
    trainingPurpose: 'Répéter précisément l\'allure/puissance cible de course.',
    physiologicalIntent: 'Spécificité — pas un objectif de performance du jour.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 3,
    minimumEffectiveDurationMin: 30,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    requiredMetric: ['ftpWatts'],
    fallbackPrescription: 'RPE (allure de course perçue).',
    explanation: 'Reproduit ton allure cible de course — la préparation la plus spécifique possible hors brick.',
    evidenceClassification: H,
  },
  // Coaching defect found during the Training Intelligence V2.1 audit
  // (brief §22, taper/race coherence): unlike SWIM_RECOVERY/RUN_RECOVERY
  // below, this family never existed even though `bike-recovery` has been
  // a real catalog template all along — `getFamilyForSession('bike',
  // 'recovery')` silently returned `undefined`, so `generateWeeklySessionRequirements`
  // (`if (!family) continue`) dropped bike's requirement with no warning
  // wherever a 'recovery' bike touch was requested: entirely in race week
  // (`PRIMARY_SESSION_TYPE_BY_PHASE.race.bike`), and as the taper phase's
  // secondary touch (`SECONDARY_SESSION_TYPE_BY_PHASE.taper.bike`) — race
  // week silently lost its bike session altogether, and taper silently
  // lost a day-slot it had already reserved for it instead of reassigning
  // it to another discipline.
  BIKE_RECOVERY: {
    id: 'BIKE_RECOVERY',
    discipline: 'bike',
    sessionType: 'recovery',
    trainingPurpose: 'Récupération active sans ajouter de fatigue.',
    physiologicalIntent: 'Circulation, décrassage musculaire.',
    appropriatePhases: ['base', 'build', 'specific', 'taper', 'race'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'RECOVERY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE très facile uniquement.',
    explanation: 'Relance les jambes sans ajouter de fatigue supplémentaire.',
    evidenceClassification: H,
  },

  // ----------------------------------------------------------------- RUN
  RUN_ENDURANCE: {
    id: 'RUN_ENDURANCE',
    discipline: 'run',
    sessionType: 'endurance',
    trainingPurpose: 'Développement aérobie, durabilité, tolérance à l\'entraînement.',
    physiologicalIntent: 'Base aérobie course à pied.',
    appropriatePhases: ['base', 'build', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'EASY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE (conversationnel).',
    explanation: 'Construit ta base aérobie course à une allure conversationnelle — jamais augmentée automatiquement chaque semaine.',
    evidenceClassification: E,
  },
  RUN_LONG: {
    id: 'RUN_LONG',
    discipline: 'run',
    sessionType: 'long',
    trainingPurpose: 'Développer l\'endurance de fond et la résistance à la fatigue.',
    physiologicalIntent: 'Base aérobie longue durée, résistance musculaire à l\'impact.',
    appropriatePhases: ['base', 'build', 'specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 40,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['BIKE_LONG'],
    fallbackPrescription: 'RPE (endurance).',
    explanation: 'Développe ta résistance à la fatigue sur la durée en course à pied.',
    evidenceClassification: E,
  },
  RUN_TEMPO: {
    id: 'RUN_TEMPO',
    discipline: 'run',
    sessionType: 'tempo',
    trainingPurpose: 'Travail sous-seuil pertinent pour la course, particulièrement important pour un M.',
    physiologicalIntent: 'Endurance musculaire, économie de course à allure soutenue.',
    appropriatePhases: ['build', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    progressionLevels: 4,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'SUPPORT',
    fatigueCost: 'moderate',
    recoveryRequirement: 0,
    requiredMetric: ['thresholdPaceSecPerKm'],
    fallbackPrescription: 'RPE (modéré-soutenu) sans allure précise tant que le seuil n\'est pas testé.',
    explanation: 'Habitue ton corps à courir vite tout en restant contrôlé — clé pour un objectif M.',
    evidenceClassification: H,
  },
  RUN_THRESHOLD: {
    id: 'RUN_THRESHOLD',
    discipline: 'run',
    sessionType: 'threshold',
    trainingPurpose: 'Développer l\'allure seuil.',
    physiologicalIntent: 'Seuil lactique/ventilatoire course à pied.',
    appropriatePhases: ['build', 'specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'secondary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 5,
    minimumEffectiveDurationMin: 25,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 1,
    incompatibleNeighbors: ['BIKE_THRESHOLD', 'RUN_VO2'],
    requiredMetric: ['thresholdPaceSecPerKm'],
    fallbackPrescription: 'RPE (seuil, 7-8/10) sans allure précise tant que le seuil n\'est pas testé.',
    explanation: 'Un Sprint met relativement plus l\'accent sur cette famille qu\'un M.',
    evidenceClassification: E,
  },
  RUN_VO2: {
    id: 'RUN_VO2',
    discipline: 'run',
    sessionType: 'intervals',
    trainingPurpose: 'Développer la VO2max et la vitesse maximale aérobie.',
    physiologicalIntent: 'VO2max course à pied, forte sollicitation cardio-respiratoire.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'minor' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 4,
    minimumEffectiveDurationMin: 20,
    defaultPriority: 'KEY_B',
    fatigueCost: 'high',
    recoveryRequirement: 2,
    incompatibleNeighbors: ['RUN_THRESHOLD', 'BIKE_VO2', 'BRICK_SPECIFIC'],
    fallbackPrescription: 'RPE (quasi-maximal, 8-9/10).',
    explanation: 'Coût physiologique élevé : utilisé sélectivement, pas simplement parce que la semaine "a besoin d\'intensité".',
    evidenceClassification: E,
  },
  RUN_STRIDES: {
    id: 'RUN_STRIDES',
    discipline: 'run',
    sessionType: 'technique',
    trainingPurpose: 'Stimulus neuromusculaire à faible volume, complément d\'un footing facile.',
    physiologicalIntent: 'Fréquence de foulée, relâchement — pas un stimulus cardiovasculaire.',
    appropriatePhases: ['build', 'specific', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'minor' },
    progressionLevels: 2,
    minimumEffectiveDurationMin: 10,
    defaultPriority: 'OPTIONAL',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'Accélération progressive, sensation, jamais à fond.',
    explanation: 'Un complément à faible coût de fatigue à un footing facile.',
    evidenceClassification: H,
  },
  RUN_RACE_SPECIFIC: {
    id: 'RUN_RACE_SPECIFIC',
    discipline: 'run',
    sessionType: 'race-specific',
    trainingPurpose: 'Répéter précisément l\'allure cible de course.',
    physiologicalIntent: 'Spécificité — reflète les exigences de la course cible plutôt qu\'une intensité générique.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 3,
    minimumEffectiveDurationMin: 25,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    requiredMetric: ['thresholdPaceSecPerKm'],
    fallbackPrescription: 'RPE (allure de course perçue).',
    explanation: 'De plus en plus pertinent à mesure qu\'on approche la phase spécifique.',
    evidenceClassification: H,
  },
  RUN_RECOVERY: {
    id: 'RUN_RECOVERY',
    discipline: 'run',
    sessionType: 'recovery',
    trainingPurpose: 'Récupération active sans ajouter de fatigue.',
    physiologicalIntent: 'Circulation, relâchement.',
    appropriatePhases: ['base', 'build', 'specific', 'taper', 'race'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'RECOVERY',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE très facile uniquement.',
    explanation: 'Relance les jambes sans créer de fatigue supplémentaire.',
    evidenceClassification: H,
  },

  // --------------------------------------------------------------- BRICK
  BRICK_ADAPTATION: {
    id: 'BRICK_ADAPTATION',
    discipline: 'brick',
    sessionType: 'brick',
    trainingPurpose: 'Adaptation de base à la transition vélo → course.',
    physiologicalIntent: 'Redistribution du flux sanguin/adaptation neuromusculaire au changement de discipline.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    progressionLevels: 2,
    minimumEffectiveDurationMin: 45,
    defaultPriority: 'KEY_B',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    fallbackPrescription: 'RPE (endurance vélo puis course).',
    explanation: 'La sensation de course juste après le vélo — la clé du triathlon, à coût relativement bas.',
    evidenceClassification: E,
  },
  BRICK_SPECIFIC: {
    id: 'BRICK_SPECIFIC',
    discipline: 'brick',
    sessionType: 'race-specific',
    trainingPurpose: 'Transition pertinente pour la course, sous fatigue contrôlée.',
    physiologicalIntent: 'Spécificité de transition à allure de course.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'primary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 2,
    minimumEffectiveDurationMin: 60,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 2,
    incompatibleNeighbors: ['BIKE_VO2', 'RUN_VO2', 'BIKE_THRESHOLD', 'RUN_THRESHOLD'],
    fallbackPrescription: 'RPE (allure de course).',
    explanation: 'Répète les allures et sensations de ta course, vélo puis course.',
    evidenceClassification: H,
  },
  BRICK_RACE_REHEARSAL: {
    id: 'BRICK_RACE_REHEARSAL',
    discipline: 'brick',
    sessionType: 'race-specific',
    trainingPurpose: 'Simulation limitée du jour de course (allures, transitions, nutrition/matériel).',
    physiologicalIntent: 'Répétition complète à charge élevée — la plus proche de la course elle-même.',
    appropriatePhases: ['specific'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'primary' },
    minimumAthleteLevel: 'intermediate',
    progressionLevels: 1,
    minimumEffectiveDurationMin: 90,
    defaultPriority: 'KEY_A',
    fatigueCost: 'high',
    recoveryRequirement: 2,
    incompatibleNeighbors: ['BIKE_VO2', 'RUN_VO2', 'BIKE_THRESHOLD', 'RUN_THRESHOLD', 'BRICK_SPECIFIC'],
    fallbackPrescription: 'RPE (allure de course) — occasion de tester nutrition/matériel.',
    explanation: "À utiliser avec parcimonie : jamais chaque semaine, seulement quand le bloc spécifique le justifie.",
    evidenceClassification: P,
  },
  TRANSITION_PRACTICE: {
    id: 'TRANSITION_PRACTICE',
    discipline: 'brick',
    sessionType: 'transition',
    trainingPurpose: 'Automatiser les gestes de transition (T1/T2).',
    physiologicalIntent: 'Coordination motrice, faible coût physiologique.',
    appropriatePhases: ['specific', 'taper'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'secondary' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'OPTIONAL',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'Pas de cible physiologique — geste et rapidité.',
    explanation: 'Gagne du temps le jour J sans stress, à coût de fatigue quasi nul.',
    evidenceClassification: P,
  },

  // ------------------------------------------------------------ STRENGTH
  STRENGTH_FOUNDATION: {
    id: 'STRENGTH_FOUNDATION',
    discipline: 'strength',
    sessionType: 'strength',
    trainingPurpose: 'Renforcer les groupes musculaires clés du triathlète.',
    physiologicalIntent: 'Squat, hinge, unijambiste, mollet, tirage/poussée, gainage anti-rotation.',
    appropriatePhases: ['base', 'build'],
    raceFormatRelevance: { sprint: 'secondary', olympic: 'secondary' },
    progressionLevels: 2,
    minimumEffectiveDurationMin: 15,
    defaultPriority: 'SUPPORT',
    fatigueCost: 'moderate',
    recoveryRequirement: 1,
    fallbackPrescription: 'RPE — charge/répétitions ajustées au ressenti, pas de 1RM requis.',
    explanation: "Renforce ta chaîne postérieure et ta stabilité pour mieux tolérer la charge d'entraînement.",
    evidenceClassification: H,
  },
  STRENGTH_MAINTENANCE: {
    id: 'STRENGTH_MAINTENANCE',
    discipline: 'strength',
    sessionType: 'strength',
    trainingPurpose: 'Maintenir les acquis de force sans consommer de récupération.',
    physiologicalIntent: 'Volume réduit — la récupération sert avant tout les séances triathlon-spécifiques.',
    appropriatePhases: ['specific', 'taper'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 10,
    defaultPriority: 'OPTIONAL',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'RPE facile — un seul tour, sans chercher la fatigue.',
    explanation:
      'Le renforcement consomme de la capacité de récupération : son volume diminue à mesure que la charge triathlon-spécifique augmente.',
    evidenceClassification: P,
  },
  MOBILITY_GENERAL: {
    id: 'MOBILITY_GENERAL',
    discipline: 'mobility',
    sessionType: 'mobility',
    trainingPurpose: 'Entretenir l\'amplitude articulaire.',
    physiologicalIntent: 'Prévenir les raideurs qui limitent la technique — pas un stimulus d\'entraînement.',
    appropriatePhases: ['base', 'build', 'specific', 'taper', 'race'],
    raceFormatRelevance: { sprint: 'minor', olympic: 'minor' },
    progressionLevels: 1,
    minimumEffectiveDurationMin: 10,
    defaultPriority: 'OPTIONAL',
    fatigueCost: 'low',
    recoveryRequirement: 0,
    fallbackPrescription: 'Aucune cible physiologique.',
    explanation: 'Prévient les raideurs qui limitent la technique dans les trois disciplines.',
    evidenceClassification: H,
  },
}

/**
 * Resolves the family for a given (discipline, sessionType) pair — the
 * only place `buildWeekSessions.ts`/the Weekly Composer need to look up
 * "what family is this slot" without hardcoding the mapping themselves.
 *
 * `BRICK_SPECIFIC` and `BRICK_RACE_REHEARSAL` intentionally share
 * `(brick, 'race-specific')` — they differ by catalog *tier* (standard vs.
 * peak), not by `SessionType`, since a full race rehearsal is the same
 * training intent at a rarer, harder exposure rather than a distinct
 * stimulus. This resolves to `BRICK_SPECIFIC` deterministically (object
 * insertion order — the everyday case), which is correct for every
 * Weekly Composer use (it requests a family to target, and the existing
 * tier system already decides which template — standard or peak — actually
 * gets picked).
 */
export function getFamilyForSession(
  discipline: WorkoutFamily['discipline'],
  sessionType: WorkoutFamily['sessionType'],
): WorkoutFamily | undefined {
  return Object.values(WORKOUT_FAMILIES).find(
    (family) => family.discipline === discipline && family.sessionType === sessionType,
  )
}
