import type { EvidenceClassification } from './evidenceClassification'
import type { FatigueCost, RecoveryRequirement } from './workoutFamily'
import type { StimulusPriority } from './stimulusPriority'
import type { SessionType } from '@/core/training/PlannedSession'
import type { Discipline } from '@/shared/types/common'

/**
 * One session the athlete needs this week, decided by coaching logic
 * *before* any calendar day is involved (Training Intelligence V2.1 —
 * "the coach decides what, the calendar decides when"). A
 * `WeeklyStimulusRequirement[]` (`sports/triathlon/coaching/weeklyStimulusComposer.ts`'s
 * `generateWeeklySessionRequirements`) is the composer's complete output
 * for the week; `buildWeekSessions.ts` then *places* each one on a real
 * day without altering what was decided.
 *
 * Deliberately sport-agnostic (like `WorkoutFamily`) even though only
 * triathlon populates it today — a future sport module produces its own
 * list of these from its own composer.
 */
export interface SessionRequirement {
  discipline: Discipline
  familyId: string
  sessionType: SessionType
  priority: StimulusPriority
  /** The duration this requirement is *composed* for — not necessarily
   * what gets scheduled: placement still fits it to the day's declared
   * availability and the catalog's authored durations. */
  preferredDurationMin: number
  /** Below this, the requirement should be replaced with an easier
   * stimulus of the same discipline (already how `pickBestFittingTemplate`'s
   * fallback chain behaves) or, if even the easiest fallback doesn't reach
   * it, dropped entirely rather than scheduled as a token session (brief
   * V2.1 §7, §26: "don't fill time for the sake of it"). Copied from the
   * family's own `minimumEffectiveDurationMin` at generation time. */
  minimumEffectiveDurationMin: number
  /** A hard placement constraint (brief V2.1 §8) — today only swim sets
   * this, but the shape generalizes to a future indoor-trainer/track/
   * open-water constraint without changing this type. */
  requiresPoolAccess: boolean
  fatigueCost: FatigueCost
  recoveryRequirement: RecoveryRequirement
  compatibleFamilies: string[]
  incompatibleFamilies: string[]
  /** Which occurrence of this discipline this is within the week (0 =
   * anchor). Decided by the composer, not derived from placement order —
   * unlike V2, where it depended on which day-claiming order a slot
   * happened to be processed in. */
  occurrenceIndex: number
  /** Structured reasons this requirement exists — the raw material for
   * "why this session"/"why this week" explanations (brief V2.1 §30),
   * never natural-language generated by an LLM. */
  reasonCodes: string[]
  evidenceClassification: EvidenceClassification
}
